# Generated by Django 5.2 on 2026-06-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('roomtype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.PositiveBigIntegerField(verbose_name='Номер')),
                ('HotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Номер отеля')),
                ('RoomTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomtype.roomtype', verbose_name='Номер типа комнаты')),
            ],
            options={
                'ordering': ['Number'],
            },
        ),
    ]
