# Generated by Django 5.2 on 2026-06-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['Number']},
        ),
        migrations.RenameField(
            model_name='room',
            old_name='idhotel',
            new_name='HotelId',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='nomber',
            new_name='Number',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='idroomtype',
            new_name='RoomTypeId',
        ),
    ]
