# Generated by Django 5.2 on 2026-06-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomtype', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='room_name',
            new_name='RoomTypeName',
        ),
    ]
