# Generated by Django 5.2 on 2026-06-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender_name',
            field=models.CharField(max_length=50, verbose_name='Имя пола'),
        ),
    ]
