# Generated by Django 5.2 on 2026-06-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0002_alter_gender_gender_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='gender_name',
            new_name='GenderName',
        ),
    ]
