# Generated by Django 5.2 on 2026-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Заселился')),
                ('checkOut', models.DateField(verbose_name='Выселился')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
            ],
            options={
                'ordering': ['comment'],
            },
        ),
    ]
