# Generated by Django 5.2 on 2026-06-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0002_guest_delete_quest'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckIn', models.DateField(verbose_name='Заселился')),
                ('CheckOut', models.DateField(verbose_name='Выселился')),
                ('Comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('GuestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.guest', verbose_name='Номер гостя')),
                ('RoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Номер комнаты')),
            ],
            options={
                'ordering': ['Comment'],
            },
        ),
    ]
