# Generated by Django 5.2 on 2026-06-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0001_initial'),
        ('guest', '0001_initial'),
        ('roomtype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='idquest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.guest', verbose_name='Номер квеста'),
        ),
        migrations.AddField(
            model_name='history',
            name='idroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomtype.roomtype', verbose_name='Номер комнаты'),
        ),
    ]
