# Generated by Django 5.2 on 2026-06-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='idroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='Номер комнаты'),
        ),
    ]
