# Generated by Django 5.2 on 2026-06-16 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_history_idroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['Comment']},
        ),
        migrations.RenameField(
            model_name='history',
            old_name='checkin',
            new_name='CheckIn',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='checkOut',
            new_name='CheckOut',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='comment',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='idquest',
            new_name='GuestId',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='idroom',
            new_name='RoomId',
        ),
    ]
