# Generated by Django 5.2 on 2026-06-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_hotel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_name',
            new_name='HotelName',
        ),
    ]
