# Generated by Django 5.2 on 2026-06-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gender', '0002_alter_gender_gender_name'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('idgender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender', verbose_name='Номер пола')),
                ('idstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status', verbose_name='Номер статуса')),
            ],
            options={
                'ordering': ['birthday'],
            },
        ),
    ]
