# Generated by Django 5.2 on 2026-06-16 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0003_rename_gender_name_gender_gendername'),
        ('guest', '0001_initial'),
        ('status', '0002_rename_status_name_status_statusname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('Birthday', models.DateField(verbose_name='Дата рождения')),
                ('GenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender', verbose_name='Номер пола')),
                ('StatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status', verbose_name='Номер статуса')),
            ],
            options={
                'ordering': ['Birthday'],
            },
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
