# Generated by Django 5.2 on 2026-06-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='StatusName',
        ),
    ]
